python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist2 --NTrees 100 --maxdepth 3 --ncuts 50 


#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1  --NTrees 25 --maxdepth 1 --ncuts 50 --overwrite 
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 1 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 1 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 1 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 1 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 1 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 1 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 1 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 1 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 1 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 1 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 1 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 1 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 1 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 1 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 1 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 1 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 1 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 1 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 1 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 1 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 2 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 2 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 2 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 2 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 2 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 2 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 2 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 2 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 2 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 2 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 2 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 2 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 2 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 2 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 2 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 2 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 2 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 2 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 2 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 2 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 3 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 3 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 3 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 3 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 3 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 3 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 3 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 3 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 3 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 3 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 3 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 3 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 3 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 3 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 3 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 3 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 3 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 3 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 3 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 3 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 4 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 4 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 4 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 4 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 4 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 4 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 4 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 4 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 4 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 4 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 4 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 4 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 4 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 4 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 4 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 4 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 4 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 4 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 4 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 4 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 5 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 5 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 5 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 25 --maxdepth 5 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 5 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 5 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 5 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 50 --maxdepth 5 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 5 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 5 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 5 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 100 --maxdepth 5 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 5 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 5 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 5 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 200 --maxdepth 5 --ncuts 400
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 5 --ncuts 50
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 5 --ncuts 100
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 5 --ncuts 200
#python train_MVA_Top_vs_TTG.py --mva bdt --variables varlist1 --NTrees 400 --maxdepth 5 --ncuts 400